CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/

testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

unittestresults: unitTest1.c unitTest2.c unitTest3.c  dominion.o rngs.o
	echo "unitTest1:" > unittestresults.out
	gcc -o test1 unitTest1.c dominion.o rngs.o $(CFLAGS)
	./test1 >> unittestresults.out
#	gcov dominion.c -b -f  >> unittestresults.out
	gcc -o test2 unitTest2.c dominion.o rngs.o $(CFLAGS)
	./test2 >> unittestresults.out
	gcc -o test3 unitTest3.c dominion.o rngs.o $(CFLAGS)
	./test3 >>unittestresults.out
	gcc -o test4 unitTest4.c dominion.o rngs.o $(CFLAGS)
	./test4 >>unittestresults.out
	gcc -o test5 unitTest5.c dominion.o rngs.o $(CFLAGS)
	./test5 >>unittestresults.out
	gcov dominion.c -b -f >> unittestresults.out
	cat dominion.c.gcov >> unittestresults.out
	
randomtestresults: randomtestcard1.c randomtestcard2.c dominion.o rngs.o
	gcc -o randomtest1 randomtestcard1.c dominion.o rngs.o $(CFLAGS)
	./randomtest1 >> unittestresults.out
	gcc -o randomtest2 randomtestcard2.c dominion.o rngs.o $(CFLAGS)
	./randomtest2 >> unittestresults.out
	gcov dominion.c -b -f >> unittestresults.out
	cat dominion.c.gcov >> unittestresults.out

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out


player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

all: playdom player randomtestresults

clean:
	rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out testDrawCard randomtest1 randomtest2 testDrawCard.exe test*
